from github import Github, Auth
import os, datetime, sys

REPO_NAME = "ChefBones323/LocalAIChatApp-"
TOKEN = os.getenv("GITHUB_TOKEN")

if not TOKEN:
    sys.exit("❌ Missing GITHUB_TOKEN environment variable. Please add it in Replit Secrets.")

print("🔑 Authenticating with GitHub...")
auth = Auth.Token(TOKEN)
g = Github(auth=auth)
repo = g.get_repo(REPO_NAME)

branch_name = f"chatgpt-update-{datetime.datetime.now().strftime('%Y%m%d%H%M%S')}"
base = repo.get_branch("main")

print(f"🌿 Creating branch: {branch_name}")
repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base.commit.sha)

FILE_PATH = "main.py"
print(f"📂 Updating file: {FILE_PATH}")
file_content = repo.get_contents(FILE_PATH, ref="main")
new_code = file_content.decoded_content.decode() + f"\n# Update committed automatically by ChatGPT on {datetime.datetime.now()}\n"

repo.update_file(
    path=FILE_PATH,
    message=f"Automated update by ChatGPT agent on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
    content=new_code,
    sha=file_content.sha,
    branch=branch_name
)

print("📦 Creating Pull Request...")
repo.create_pull(
    title=f"ChatGPT Automated Update ({datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')})",
    body="This pull request was automatically generated by ChatGPT using your GitHub token in Replit.",
    head=branch_name,
    base="main"
)

print("✅ Pull Request created successfully! Check your GitHub repo to review and merge.")
